import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./shared/styles/globals.css";
import { Providers } from "./shared/utils/Provider";
import localFont from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

const clashDisplay = localFont({
  src : '../app/assets/fonts/ClashDisplay-Variable.ttf',
  variable : '--font-clashDisplay',
  weight : '700',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
